### ISSUE TITLE
Update Chatowner node to store just a reference not entire user info

### ISSUE THREAD

**Issue by ychino** [awesomechat/craigschat#31]
Chatowner node should store just a reference uid as we discussed.

Then it reference the user in the users node by using the reference id.

@IniZio Question. In this approach, let's say user ABC updated their profile image, do you know how we could listen the change event to reflect the new image in the chatroom list card?

I want to know this for when we do the same for roommembers and want to listen online status changes in associated users to show current room members online status in the chatroom.

**Comment by IniZio** [comment]
Yea so i am thinking having a container, when passed in user id it will return a Promise of its profile

It will also listen for change in that user id, so online status can be synced as well

**Comment by ychino** [comment]
@InIZio thank you for your replay. Ok, I will give it a shot for roommembers for now and create a PR shortly. Thank you!

**Comment by IniZio** [comment]
Oh already doing it here https://github.com/awesomechat/craigschat/tree/feature/%2331-refer-user-info

**Comment by IniZio** [comment]
Because i want to memoize the user profiles, so i have the cache. And also i don't want to make multiple requests for same user id so i used `onLoad`, which is easier done with state?

**Comment by ychino** [comment]
Work to store just a uid of user, not entire object, needs to be done before closing this
