### ISSUE TITLE
Save/Update Image and Logo for Chatroom and show them in ListCard

### ISSUE THREAD

**Issue by ychino** [awesomechat/craigschat#59]
User should be able to add image and Logo to a chatroom when it's created and change the image with another one from the edit details page

Images should be shown upper side of cards in Home as follows and Logo can be placed somewhere. I guess right next to divs for owner name and place 
![card](https://user-images.githubusercontent.com/16337251/50962918-a72d4c80-150e-11e9-8f2d-a19bda73b921.PNG)

**Comment by IniZio** [comment]
Maybe let user set a chatroom icon also? like a logo or something

**Comment by ychino** [comment]
That's good idea. Ticket has been updated.
