### ISSUE TITLE
Avatars overflow in ListCard in Home

### ISSUE THREAD

**Issue by ychino** [awesomechat/craigschat#66]
If room members (excluding room owner) are more than 5 members, then it lists just a number of rest of members.  
![image](https://user-images.githubusercontent.com/16337251/51364507-b5d3bf00-1b1f-11e9-87f9-86e79e20e082.png)

If a room has 9 members, it should list 5 avatars and `+4`. An example is as follows;

![image](https://user-images.githubusercontent.com/16337251/51364464-9ccb0e00-1b1f-11e9-8028-ce4da48ea7b9.png)

**Comment by jcolborn-dropdeadgames** [comment]
If no one has picked this up yet, can I go ahead and start working on it?

**Comment by ychino** [comment]
Sure, thank you for your help in advance!

**Comment by ychino** [comment]
@jcolborn-dropdeadgames I'm wondering how difficult to show avatars as below? If it's difficult, please ignore this :)

![image](https://user-images.githubusercontent.com/16337251/51453718-617d4900-1d84-11e9-92f6-c43febf637c6.png)

**Comment by ychino** [comment]
Sound good. Thank you!
