### ISSUE TITLE
When user logs off after using filter, all chatrooms are not listed

### ISSUE THREAD

**Issue by ychino** [awesomechat/craigschat#92]
1. Login to the app
2. Click `Chatrooms you own` to filter chatrooms
3. Log off
4. Then all chatrooms should be rendered but currently only chatrooms filtered earlier are listed

**Comment by IniZio** [comment]
So should reset filter on logout?

**Comment by ychino** [comment]
Yes, that would be great :)

**Comment by ychino** [comment]
Also, reset filter being logged in would be great as well :)
